COMP: Fix build error removing unneeded install of multiprocessing
Starting with Python 2.6, multiprocessing package is available in
python and there is no need to explicitly install the package from
pypi.

This commit fixes the following error:

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-vg5p84hs/multiprocessing/setup.py", line 94
      print 'Macros:'
                    ^
  SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Macros:')?